name: study_pal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_storage: ^10.0.4
  fl_chart: ^0.36.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^6.0.0
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  hive: ^2.0.4
  http: ^0.13.3
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  sizer: ^2.0.13
  timeago: ^3.1.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/boy.jpg
    - assets/images/girl.jpg
    - assets/images/auth.jpeg
    - assets/images/bg_art.png
    - assets/images/bg_bottom_art.png
    - assets/images/bg_top_art.png
    - assets/images/stu_no_txt.png
    - assets/images/stu_text.png
    - assets/images/homet.png
    - assets/images/autht.png
    - assets/images/authw.jpg
    - assets/images/done.png
